apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discount-sqlite-data
  namespace: eshop-microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  # Bỏ storageClassName để sử dụng StorageClass mặc định
  # storageClassName: hostpath