apiVersion: v1
kind: ConfigMap
metadata:
  name: eshop-config
  namespace: eshop-microservices
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ConnectionStrings__EventBusConnection: "rabbitmq"
  MessageBroker__Host: "amqp://rabbitmq:5672"
  MessageBroker__UserName: "guest"
  MessageBroker__Password: "guest"