apiVersion: v1
kind: ConfigMap
metadata:
  name: eshop-config
  namespace: eshop-microservices
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ConnectionStrings__EventBusConnection: "rabbitmq"
  EventBusSettings__HostAddress: "amqp://guest:guest@rabbitmq:5672"