apiVersion: v1
kind: Secret
metadata:
  name: eshop-secrets
  namespace: eshop-microservices
type: Opaque
stringData:
  JwtSettings__Key: "727410b36cdc4b5c8ac91011dd2083db8381aa7b07d245b787800a5e263f525a"
  JwtSettings__Issuer: "authservice"
  JwtSettings__Audience: "eshop-apis"