{
 "title": "Kubernetes Pods",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Pod CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"eshop-microservices\"}[1m])) by (pod)"
    }
   ]
  }
 ]
}
{
 "title": "EShop Products Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Products Count",
   "type": "graph",
   "description": "Total number of products in catalog",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "catalog_total_products" }
   ]
  }
 ]
}
{
 "title": ".NET Runtime Metrics",
 "tags": [
  "dotnet",
  "runtime"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": ".NET GC Collection Rate",
   "type": "graph",
   "description": ".NET Runtime GC Collection Count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Collections/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dotnet_gc_collection_count_total[1m])) by (instance, generation)"
    }
   ]
  },
  {
   "title": ".NET Heap Size",
   "type": "graph",
   "description": ".NET Heap Size",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Size" }
   ],
   "targets": [
    {
     "expr": "sum(dotnet_gc_heap_size_bytes) by (instance)"
    }
   ]
  },
  {
   "title": ".NET Thread Pool Size",
   "type": "graph",
   "description": ".NET Thread Pool Size",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "expr": "sum(dotnet_threadpool_thread_count) by (instance)"
    }
   ]
  },
  {
   "title": ".NET Exceptions Thrown Rate",
   "type": "graph",
   "description": ".NET Exceptions Thrown",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Exceptions/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dotnet_exceptions_thrown_total[1m])) by (instance)"
    }
   ]
  }
 ]
}