http:
  routers:
    auth-router:
      rule: "PathPrefix(`/auth-service`)"
      service: auth-service
      middlewares:
        - strip-auth-prefix
        - rate-limit
        
    catalog-router:
      rule: "PathPrefix(`/catalog-service`)"
      service: catalog-service
      middlewares:
        - strip-catalog-prefix
        - rate-limit
        - jwt-auth
        
    basket-router:
      rule: "PathPrefix(`/basket-service`)"
      service: basket-service
      middlewares:
        - strip-basket-prefix
        - rate-limit
        - jwt-auth
        
    ordering-router:
      rule: "PathPrefix(`/ordering-service`)"
      service: ordering-service
      middlewares:
        - strip-ordering-prefix
        - rate-limit
        - jwt-auth
        
  middlewares:
    strip-auth-prefix:
      stripPrefix:
        prefixes:
          - "/auth-service"
          
    strip-catalog-prefix:
      stripPrefix:
        prefixes:
          - "/catalog-service"
          
    strip-basket-prefix:
      stripPrefix:
        prefixes:
          - "/basket-service"
          
    strip-ordering-prefix:
      stripPrefix:
        prefixes:
          - "/ordering-service"
    
    rate-limit:
      rateLimit:
        average: 50
        burst: 20
        period: 1s
    
    # JWT Auth middleware sử dụng ForwardAuth để xác thực với Auth Service
    jwt-auth:
      forwardAuth:
        address: "http://auth-api-1:80/api/auth/validate-token"
        authResponseHeaders:
          - "Authorization"
        trustForwardHeader: true
        
  services:
    auth-service:
      loadBalancer:
        servers:
          - url: "http://auth-api-1:80"
        
    catalog-service:
      loadBalancer:
        servers:
          - url: "http://catalog-api-1:80"
          - url: "http://catalog-api-2:80"
          - url: "http://catalog-api-3:80"
        
    basket-service:
      loadBalancer:
        servers:
          - url: "http://basket-api-1:80"
        
    ordering-service:
      loadBalancer:
        servers:
          - url: "http://ordering-api-1:80"