apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limiting
  namespace: eshop-microservices
plugin: rate-limiting
config:
  second: 50
  policy: local
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: auth-path-transformer-login
  namespace: eshop-microservices
plugin: request-transformer
config:
  replace:
    uri: "/api/auth/login"
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: auth-path-transformer-register
  namespace: eshop-microservices
plugin: request-transformer
config:
  replace:
    uri: "/api/auth/register"
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: jwt-auth
  namespace: eshop-microservices
plugin: jwt
config:
  claims_to_verify:
  - exp
  key_claim_name: iss
  run_on_preflight: false
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: microservice-clients
  namespace: eshop-microservices
username: microservice-clients
---
apiVersion: v1
kind: Secret
metadata:
  name: microservice-clients-jwt
  namespace: eshop-microservices
  labels:
    konghq.com/credential: jwt
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/consumer: microservice-clients
type: Opaque
stringData:
  key: "authservice"
  algorithm: "HS256"
  secret: "727410b36cdc4b5c8ac91011dd2083db8381aa7b07d245b787800a5e263f525a"
  iss: "authservice"