apiVersion: v1
kind: Namespace
metadata:
  name: eshop-microservices
  labels:
    name: eshop-microservices
---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway
  labels:
    name: gateway
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
