global using Microsoft.EntityFrameworkCore;
global using Ordering.Domain.Models;
global using BuildingBlocks.CQRS;
global using FluentValidation;
global using Ordering.Application.Dtos;
global using Ordering.Application.Data;
global using Ordering.Domain.ValueObjects;
global using BuildingBlocks.Exceptions;
global using Ordering.Application.Exceptions;
