apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basket-postgres-pvc
  namespace: eshop-microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-postgres
  namespace: eshop-microservices
spec:
  selector:
    matchLabels:
      app: basket-postgres
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: basket-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14.1
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "BasketDb"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          limits:
            memory: 512Mi
            cpu: "0.5"
          requests:
            memory: 256Mi
            cpu: "0.2"
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: basket-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: basket-postgres
  namespace: eshop-microservices
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: basket-postgres
