version: '3.4'

services:
  catalogdb:
    image: postgres:16
    networks:
      - microservices-network

  basketdb:
    image: postgres:16
    networks:
      - microservices-network

  distributedcache:
    image: redis
    networks:
      - microservices-network

  orderdb:
    image: mcr.microsoft.com/mssql/server
    networks:
      - microservices-network

  authdb:
    image: postgres:16
    networks:
      - microservices-network

  messagebroker:
    image: rabbitmq:management
    networks:
      - microservices-network

  catalog-api-1:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    networks:
      - microservices-network

  catalog-api-2:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    networks:
      - microservices-network

  catalog-api-3:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    networks:
      - microservices-network

  auth-api-1:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: Services/Auth/Auth.API/Dockerfile
    networks:
      - microservices-network

  basket-api-1:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    networks:
      - microservices-network

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.gRPC/Dockerfile
    networks:
      - microservices-network

  ordering-api-1:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    networks:
      - microservices-network
      
  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile
    networks:
      - microservices-network
    profiles:
      - yarp

  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGateway/Dockerfile
    networks:
      - microservices-network
    profiles:
      - ocelot

  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"
    networks:
      - microservices-network
      
  # Kong API Gateway and database
  kong-database:
    image: postgres:16
    container_name: kong-database
    networks:
      - microservices-network
    profiles:
      - kong
      
  kong-migration:
    image: kong:3.4.2
    command: kong migrations bootstrap
    networks:
      - microservices-network
    depends_on:
      - kong-database
    restart: on-failure
    profiles:
      - kong
      
  kong:
    image: kong:3.4.2
    container_name: kong
    networks:
      - microservices-network
    depends_on:
      - kong-database
      - kong-migration
    profiles:
      - kong
      
  kong-setup:
    image: ${DOCKER_REGISTRY-}kong-setup
    build:
      context: .
      dockerfile: ApiGateways/KongApiGateway/Dockerfile
    networks:
      - microservices-network
    depends_on:
      - kong
    profiles:
      - kong

  # Traefik API Gateway
  traefik:
    image: traefik:v2.10
    container_name: traefik
    networks:
      - microservices-network
    depends_on:
      - catalog-api-1
      - catalog-api-2
      - catalog-api-3
      - basket-api-1
      - ordering-api-1
      - auth-api-1
    profiles:
      - traefik
      
  # Traefik setup container
  traefik-setup:
    image: ${DOCKER_REGISTRY-}traefik-setup
    build:
      context: .
      dockerfile: /ApiGateways/TraefikApiGateway/Dockerfile
    networks:
      - microservices-network
    depends_on:
      - traefik
    profiles:
      - traefik

volumes:
  postgres_catalog:
  postgres_basket:
  postgres_auth:
  postgres_kong:
  traefik-config:

networks:
  microservices-network:
    driver: bridge
